### ISSUE TITLE
Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by ivan-streun** [teamookla/speedtest-tools#2]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the teamookla/speedtest tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/teamookla/homebrew-speedtest/speedtest.rb:7

**Comment by cylllllll** [comment]
same problem

**Comment by wbills** [comment]
Wrong repo: https://github.com/teamookla/homebrew-speedtest
