### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by baqwas** [teamookla/speedtest-tools#4]
```
The repository is setup! You can now install packages.
$ sudo apt install -y speedtest
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package speedtest
$ 
$ uname -a
Linux hostname 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
$

```
What is the workaround, please?

**Comment by wbills** [comment]
You need to add the repository first (found under Install Options for CLI here: https://www.speedtest.net/apps/cli):

curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash

sudo apt-get install speedtest

**Comment by baqwas** [comment]
Thanks for helping out a _newbie_ who forgot about RTM (_i.e._ Rule 101 before seeking help).

Regards.

**Comment by seanmacgillivray** [comment]
I found that I had to refer to the package as `speedtest-cli` to get Apt to install it, once I'd added the repo:

`sudo apt-get install speedtest-cli`

Ubuntu 24.04 LTS

**Comment by armujahid** [comment]
@seanmacgillivray that speedtest-cli is a different package that isn't maintained by ookla https://launchpad.net/ubuntu/+source/speedtest-cli


For ubuntu 24.04 LTS you need to manually update release name sources in /etc/apt/sources.list.d/ookla_speedtest-cli.list to jammy like

`deb [signed-by=/etc/apt/keyrings/ookla_speedtest-cli-archive-keyring.gpg] https://packagecloud.io/ookla/speedtest-cli/ubuntu/ jammy main
`

Reason is Ubuntu 24.04LTS release file a.k.a noble isn't yet available. @teamookla can you add release file for 24.04 ?

**Comment by karthikjagannathan** [comment]
> [@seanmacgillivray](https://github.com/seanmacgillivray) that speedtest-cli is a different package that isn't maintained by ookla https://launchpad.net/ubuntu/+source/speedtest-cli
> 
> For ubuntu 24.04 LTS you need to manually update release name sources in /etc/apt/sources.list.d/ookla_speedtest-cli.list to jammy like
> 
> `deb [signed-by=/etc/apt/keyrings/ookla_speedtest-cli-archive-keyring.gpg] https://packagecloud.io/ookla/speedtest-cli/ubuntu/ jammy main `
> 
> Reason is Ubuntu 24.04LTS release file a.k.a noble isn't yet available. [@teamookla](https://github.com/teamookla) can you add release file for 24.04 ?

thank you! been breaking my head on this for the past two days trying to figure out why speedtest won't install on my ubuntu docker container when it worked just fine on the prior release.
